- pipeline: android_ci
  name: Android CI
  actions:
  - action: npx cap sync android
    type: BUILD
    execute_commands:
    - "# yarn install"
    - npm install
    - npm run build
    - npx cap sync android
    shell: BASH
    docker_image_name: library/node
    docker_image_tag: 24
  - action: npm test
    type: BUILD
    execute_commands:
    - "# yarn install"
    - npm install
    - npm test
    shell: BASH
    docker_image_name: library/node
    docker_image_tag: 24
